<a href="https://colab.research.google.com/github/DiegoMeseguer/pytorch-tutorial/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#00. Pytorch Fundamentals
Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/ \
If you have questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [212]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


In [213]:
!ls -la
!pwd
!echo "hello world"
!nvidia-smi


total 16
drwxr-xr-x 1 root root 4096 Apr 18 13:25 .
drwxr-xr-x 1 root root 4096 Apr 21 22:08 ..
drwxr-xr-x 4 root root 4096 Apr 18 13:24 .config
drwxr-xr-x 1 root root 4096 Apr 18 13:25 sample_data
/content
hello world
Sun Apr 21 22:13:53 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P0            

# Introduction to Tensors
## Creating Tensors

Pytorch tensor are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [214]:
# Scalar
scalar = torch.tensor(7)
scalar
print(type(scalar))
print(isinstance(scalar, torch.Tensor))
print(isinstance(scalar, dict))



<class 'torch.Tensor'>
True
False


In [215]:
scalar.ndim, scalar.shape

(0, torch.Size([]))

In [216]:
# Get tensor back as Python int
scalar.item()
number = scalar.item()
print(number)
print(type(number))

7
<class 'int'>


In [217]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [218]:
vector.ndim

1

In [219]:
vector.shape

torch.Size([2])

In [220]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [221]:
MATRIX.ndim

2

In [222]:
MATRIX[0][0]

tensor(7)

In [223]:
MATRIX[1]

tensor([ 9, 10])

In [224]:
MATRIX.shape

torch.Size([2, 2])

In [225]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [226]:
TENSOR.ndim

3

In [227]:
TENSOR.shape

torch.Size([1, 3, 3])

In [228]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [229]:
TENSOR[0][0][2]

tensor(3)

### Random Tensors

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html#torch.rand

In [230]:
# Create a random tensor of size (3, 4)
randomTensor = torch.rand(3, 4)
randomTensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [231]:
randomTensor.ndim

2

In [232]:
randomTensor.shape

torch.Size([3, 4])

In [233]:
# Create a random tensor with similar shape to an image tensor
randomImageSizeTensor = torch.rand(size=(224, 224, 3)) # height, width, color channels
randomImageSizeTensor.ndim, randomImageSizeTensor.shape


(3, torch.Size([224, 224, 3]))

In [234]:
randomTensor2 = torch.rand(size=(10,5,12,1,5))
randomTensor2.ndim, randomTensor2.shape

(5, torch.Size([10, 5, 12, 1, 5]))

### Zeros and Ones

In [235]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [236]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [237]:
ones.dtype

torch.float32

In [238]:
randomTensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [239]:
# torch.range() is deprecated, use torch.arange() instead
oneToTen = torch.arange(start=1, end=11, step=1)
oneToTen, oneToTen.dtype

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.int64)

In [240]:
# Creating tensors like
tenZeros = torch.zeros_like(input=oneToTen)
tenZeros, tenZeros.dtype

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.int64)

### Tensor datatypes

**Note:** Tensor datatypes is one of the three big errors you will run into with Pytorch and deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in CS - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [241]:
# Float 32 tensor
float32Tensor = torch.tensor([3.0, 6.0, 9.0],
                             dtype=None,          # What datatype is the tensor (e.g. float32 or float16)
                             device='cpu',        # What device is your tensor on
                             requires_grad=False) # whether or not to track gradients with this tensors' operations
float32Tensor, float32Tensor.ndim, float32Tensor.shape

(tensor([3., 6., 9.]), 1, torch.Size([3]))

In [242]:
float32Tensor.dtype

torch.float32

In [243]:
float16Tensor = float32Tensor.type(torch.float16)
float16Tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [244]:
newTensor = float16Tensor * float32Tensor
newTensor

tensor([ 9., 36., 81.])

In [245]:
type(newTensor), newTensor.ndim, newTensor.dtype, newTensor.shape

(torch.Tensor, 1, torch.float32, torch.Size([3]))

In [246]:
int32Tensor = torch.tensor([3, 6, 9],
                           dtype=torch.int32)
int32Tensor

tensor([3, 6, 9], dtype=torch.int32)

In [247]:
newNewTensor = float32Tensor * int32Tensor
newNewTensor

tensor([ 9., 36., 81.])

In [248]:
newNewTensor.ndim, newNewTensor.dtype

(1, torch.float32)

### Getting information from tensors (tensor attributes)
1. Tensors not right datatype - to get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [249]:
# Create a tensor
someTensor = torch.rand(3, 4)
someTensor

tensor([[0.4218, 0.0354, 0.4598, 0.7218],
        [0.8727, 0.8555, 0.7336, 0.6122],
        [0.9896, 0.8666, 0.7785, 0.2229]])

In [250]:
# Find out details about someTensor
print(someTensor)
print(f"Datatype of tensor: {someTensor.dtype}")
print(f"Shape of tensor: {someTensor.shape}")
print(f"Device tensor is on: {someTensor.device}")

tensor([[0.4218, 0.0354, 0.4598, 0.7218],
        [0.8727, 0.8555, 0.7336, 0.6122],
        [0.9896, 0.8666, 0.7785, 0.2229]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [251]:
test = torch.Tensor([])
test.ndim, test.shape, test, test.dtype

(1, torch.Size([0]), tensor([]), torch.float32)

In [252]:
test2 = torch.tensor(4)
test2.ndim, test2.shape, test2, test2.dtype

(0, torch.Size([]), tensor(4), torch.int64)

In [253]:
torch.get_default_dtype()

torch.float32

In [254]:
myTensor = torch.tensor([3.0, 6.0, 9.0],
                        dtype=torch.float64,
                        device="cuda")
print(myTensor)
print(f"Datatype of tensor: {myTensor.dtype}")
print(f"Shape of tensor: {myTensor.shape}")
print(f"Device tensor is on: {myTensor.device}")

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float64)
Datatype of tensor: torch.float64
Shape of tensor: torch.Size([3])
Device tensor is on: cuda:0


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [255]:
# Create a tensor and add ten to it
anotherTensor = torch.tensor([1, 2, 3])
anotherTensor.dtype
anotherTensor + 10, anotherTensor


(tensor([11, 12, 13]), tensor([1, 2, 3]))

In [256]:
# Multiply tensor by ten
10 * anotherTensor

tensor([10, 20, 30])

In [257]:
# Subtract ten from tensor
anotherTensor - 10

tensor([-9, -8, -7])

In [258]:
# You can also use Pytorch built-in functions
torch.mul(anotherTensor, 10), anotherTensor

(tensor([10, 20, 30]), tensor([1, 2, 3]))

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [259]:
# Element-wise multiplication
print(anotherTensor)
print(anotherTensor, "*", anotherTensor)
print(f"Equals: {anotherTensor * anotherTensor}")

tensor([1, 2, 3])
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [260]:
# Matrix multiplication
print(torch.matmul(anotherTensor, anotherTensor))
print(anotherTensor.shape)


tensor(14)
torch.Size([3])


In [261]:
pachelbel = torch.matmul(anotherTensor, anotherTensor)
pachelbel, pachelbel.shape, pachelbel.ndim

(tensor(14), torch.Size([]), 0)

In [262]:
# Matrix multiplication by hand
%%time
sum = 0
for i in range(len(anotherTensor)):
  sum += anotherTensor[i] * anotherTensor[i]
  print(sum)
print(sum)

tensor(1)
tensor(5)
tensor(14)
tensor(14)
CPU times: user 1e+03 µs, sys: 1 µs, total: 1 ms
Wall time: 2.02 ms


In [263]:
%%time
torch.matmul(anotherTensor, anotherTensor)

CPU times: user 40 µs, sys: 0 ns, total: 40 µs
Wall time: 42.2 µs


tensor(14)

### Intermezzo: A first use of:

`torch.nn.linear()`

The torch.nn.Linear() module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix A.

`y = x ⋅ AT + b`

Where:\
`x` is the input to the layer\
`A` is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (the weight matrix gets transposed)
`b` is the bias term, used to slightly offset the weights and inputs\
`y` is the output


In [264]:
# Let's play aroudn with a linear layer
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=3, # in_features = matches inner dimension of input
                         out_features=6)  #out_features = describes outer value
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]], dtype=torch.float32)
output = linear(x.T)
print(f"Input shape {x.T.shape}\n")
print(f"Output:\n {output}\n Output shape: {output.shape}")

Input shape torch.Size([2, 3])

Output:
 tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)
 Output shape: torch.Size([2, 6])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [265]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.ndim, x.shape

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), 1, torch.Size([10]))

In [266]:
#Find the min
torch.min(x), x.min(), x.min().ndim, x.min().shape

(tensor(0), tensor(0), 0, torch.Size([]))

In [267]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [268]:
#Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float64).mean()

(tensor(45.), tensor(45., dtype=torch.float64))

In [269]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [270]:
# Find the position in tensor that has the min value and the position that has the max value
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [271]:
x[9]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape, but keep the same memory as the orginal tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [272]:
# Let's create a tensor
y = torch.arange(1., 10.)
y, y.ndim, y.shape, y.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 1,
 torch.Size([9]),
 torch.float32)

In [273]:
# Add an extra dimension
y_reshaped = y.reshape(1, 9)
y_reshaped, y_reshaped.ndim, y_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), 2, torch.Size([1, 9]))

In [274]:
# Change the view
z = y.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [275]:
# Changing z also changes y (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z, y

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [276]:
# Stack tensors on top of each other
y_stacked = torch.stack([y, y, y, y], dim=0)
y_stacked, y_stacked.ndim, y_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 2,
 torch.Size([4, 9]))

In [277]:
# Squeeze with torch.squeeze() - removes all single dimensions from a target tensor
y_squeezed = torch.squeeze(y_reshaped)
y_squeezed, y_squeezed.shape, y_reshaped, y_reshaped.shape, y, y.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]))

In [278]:
y_reshaped.squeeze(), y_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [279]:
# Let's check if squeeze also gives a view (it does)
y_squeezed[8] = 65
y_squeezed, y_squeezed.shape, y_reshaped, y_reshaped.shape, y, y.shape

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 65.]),
 torch.Size([9]),
 tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 65.]]),
 torch.Size([1, 9]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 65.]),
 torch.Size([9]))

In [280]:
# Unsqueeze with torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension
print(f"Previous target: {y_squeezed}")
print(f"Previous shape: {y_squeezed.shape}")


# Add an extra dimension with unsqueeze
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
print(f"New tensor: {y_unsqueezed}")
print(f"New shape: {y_unsqueezed.shape}")

Previous target: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 65.])
Previous shape: torch.Size([9])
New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8., 65.]])
New shape: torch.Size([1, 9])


In [281]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(2,3))
x_original

tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])

In [282]:
x_random = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]
x_random.shape


torch.Size([224, 224, 3])

In [283]:
# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_random.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 224])

In [284]:
# Permute returns a view of the original tensor and a view shares the same memory as the original tensor
x_original_permuted = x_original.permute(1, 0)
x_original_permuted[2,1] = 777.777
x_original_permuted, x_original



(tensor([[1.0531e-01, 1.9936e-01],
         [2.6949e-01, 5.4719e-01],
         [3.5881e-01, 7.7778e+02]]),
 tensor([[1.0531e-01, 2.6949e-01, 3.5881e-01],
         [1.9936e-01, 5.4719e-01, 7.7778e+02]]))

### Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [285]:
# Create a tensor
gamma = torch.arange(1, 10)
gamma = gamma.reshape(1, 3, 3)
gamma, gamma.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [286]:
# Let's index on our new tensor
gamma[0,0,0], gamma[0, 2]

(tensor(1), tensor([7, 8, 9]))

In [287]:
gamma[0,1,1]

tensor(5)

In [288]:
# Get number 9
gamma[0,2,2]

tensor(9)

In [289]:
# You can also use ":" to select "all" of a target dimension
gamma[:, 0]

tensor([[1, 2, 3]])

In [290]:
gamma[:, :, 0], gamma[:, :, 0].shape

(tensor([[1, 4, 7]]), torch.Size([1, 3]))

In [291]:
# Get all values of 0th and 1st dimensions, but only index 1 of 2nd dimension
gamma[:, :, 1]

tensor([[2, 5, 8]])

In [292]:
# Get all values of the 0th dimension, but only the 1 index value of the 1st and 2nd dimensions
gamma[:, 1, 1]

tensor([5])

In [293]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
gamma[0, 0, :]

tensor([1, 2, 3])

In [294]:
# Index to return 9
gamma[0, 2, 2], gamma[0][2][2]
# Index to return 3, 6, 9
gamma[0, :, 2]

tensor([3, 6, 9])

### PyTorch tensors & NumPy
NumPy is a popular scientific Python numerical computing library.\
And because of this, PyTorch has functionality to interact with it.
- Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
- PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`


In [295]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
array, type(array), array.shape, array.dtype
my_tensor = torch.from_numpy(array)
my_tensor, array, array.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'))

In [296]:
# If we want the default data type that PyTorch uses
my_tensor_02 = torch.from_numpy(array).type(torch.float32)
my_tensor_02, my_tensor_02.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [297]:
# Change the value of the numpy array. What will this do to the tensor?
array = array + 1
array, my_tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [298]:
# Tensor to numpy array
tensor_abc = torch.ones(4, 2)
tensor_abc, tensor_abc.shape, tensor_abc.ndim
numpy_tensor = tensor_abc.numpy()
tensor_abc, numpy_tensor, type(numpy_tensor)

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32),
 numpy.ndarray)

In [299]:
# Change the tensor, what happens to the "numpy_tensor"?
tensor_abc = tensor_abc + 1
tensor_abc, numpy_tensor

(tensor([[2., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32))

### Reproducibility (tring to take random out of random)
In short, how a neural network learn:\
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [300]:
torch.rand(3, 3)

tensor([[0.9536, 0.6002, 0.0351],
        [0.6826, 0.3743, 0.5220],
        [0.1336, 0.9666, 0.9754]])

In [301]:
# Create two random tensors
random_A = torch.rand(3, 4)
random_B = torch.rand(3, 4)

print(random_A)
print(random_B)
print(random_A == random_B)

tensor([[0.8474, 0.8988, 0.1105, 0.4563],
        [0.9719, 0.3968, 0.1496, 0.4743],
        [0.9973, 0.4436, 0.9726, 0.5194]])
tensor([[0.5337, 0.7050, 0.3362, 0.7891],
        [0.1694, 0.1800, 0.7177, 0.6988],
        [0.5510, 0.2485, 0.8518, 0.0963]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [302]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3, 4)

print(random_C)
print(random_D)
print(random_C == random_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed
* https://towardsdatascience.com/random-seeds-and-reproducibility-933da79446e3

### Running tensors and PyTorch objects on the GPUs (and making faster computations)
GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options... See this post for more advice https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure... these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) take a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [303]:
!nvidia-smi

Sun Apr 21 22:13:54 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P0              27W /  70W |    121MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [304]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

### For PyTorch, since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

e.g. run on GPU if available, else run on CPU



In [305]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [306]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [307]:
# Create a tensor (default on the CPU)
beta = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(beta, beta.device)


tensor([1, 2, 3]) cpu


In [308]:
# Move tensor to GPU (if available)
tensor_on_gpu = beta.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

### 4. Moving tensors back to the CPU

In [309]:
# If tensor is on GPU, can't transform it to NumPy
# tensor_on_gpu.numpy() gives en error

In [310]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu.numpy(), tensor_back_on_cpu.numpy().dtype, type(tensor_back_on_cpu.numpy())

(array([1, 2, 3]), dtype('int64'), numpy.ndarray)

In [311]:
# Modidying the numpy array doesn't affect the tensor on gpu or cpu
alf = tensor_back_on_cpu.numpy()
alf = alf + 1
alf, beta, tensor_on_gpu, tensor_back_on_cpu

(array([2, 3, 4]),
 tensor([1, 2, 3]),
 tensor([1, 2, 3], device='cuda:0'),
 tensor([1, 2, 3]))

In [312]:
# Modifying the original tensor on cpu doesn't seem to change the new tensor we took back to the cpu from the gpu
beta = beta + 1
tensor_back_on_cpu = tensor_back_on_cpu + 10
alf, beta, tensor_on_gpu, tensor_back_on_cpu

(array([2, 3, 4]),
 tensor([2, 3, 4]),
 tensor([1, 2, 3], device='cuda:0'),
 tensor([11, 12, 13]))

In [313]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')