<a href="https://colab.research.google.com/github/DiegoMeseguer/pytorch-tutorial/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)
!nvidia-smi

Sat May 11 18:13:57 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
import torch
print(torch.__version__)

sven = torch.rand(7, 7)
sven, sven.shape, sven.dtype,  sven.device, sven.ndim

2.2.1+cu121


(tensor([[0.8758, 0.2496, 0.5375, 0.8382, 0.2527, 0.2681, 0.8490],
         [0.5302, 0.0038, 0.2588, 0.0453, 0.8598, 0.5088, 0.5850],
         [0.8460, 0.3368, 0.7962, 0.6170, 0.6722, 0.3977, 0.2346],
         [0.3176, 0.5430, 0.4186, 0.4310, 0.4046, 0.6610, 0.7577],
         [0.4586, 0.1348, 0.3262, 0.4604, 0.0812, 0.2068, 0.6905],
         [0.1351, 0.3435, 0.9495, 0.5467, 0.9682, 0.0667, 0.9228],
         [0.6666, 0.5898, 0.8092, 0.9952, 0.1049, 0.7884, 0.5596]]),
 torch.Size([7, 7]),
 torch.float32,
 device(type='cpu'),
 2)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
secondTensor = torch.rand(1, 7)
multResult = torch.matmul(sven, secondTensor.T)
multResult, multResult.shape, multResult.dtype, multResult.device, multResult.ndim

(tensor([[2.6717],
         [2.0641],
         [2.6831],
         [2.8015],
         [1.6960],
         [3.3482],
         [3.2421]]),
 torch.Size([7, 1]),
 torch.float32,
 device(type='cpu'),
 2)

In [ ]:
aplastado = torch.squeeze(multResult)
aplastado, aplastado.shape

(tensor([2.6717, 2.0641, 2.6831, 2.8015, 1.6960, 3.3482, 3.2421]),
 torch.Size([7]))

In [ ]:
alargado = aplastado.unsqueeze(dim=1)
alargado, alargado.shape

(tensor([[2.6717],
         [2.0641],
         [2.6831],
         [2.8015],
         [1.6960],
         [3.3482],
         [3.2421]]),
 torch.Size([7, 1]))

In [ ]:
print(alargado == multResult)

tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True],
        [True]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

alpha = torch.rand(7, 7)
beta = torch.rand(1, 7)
gamma = torch.matmul(alpha, beta.T)

gamma, gamma.shape, gamma.dtype, gamma.ndim

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]),
 torch.float32,
 2)

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
torch.cuda.is_available(), torch.cuda.device_count(), torch.cuda.current_device(), torch.cuda.get_device_name(0)


(True, 1, 0, 'Tesla T4')

In [ ]:
GPU_RANDOM_SEED = 1234
torch.cuda.manual_seed(GPU_RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
NEW_RANDOM_SEED = 1234
torch.manual_seed(NEW_RANDOM_SEED)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(a, a.device)
print(b, b.device)

a_on_gpu = a.to(device)
b_on_gpu = b.to(device)
print(a_on_gpu)
print(b_on_gpu)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) cpu
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]]) cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
cudaResult = torch.matmul(a_on_gpu, b_on_gpu.T)
cudaResult, cudaResult.shape, cudaResult.dtype, cudaResult.ndim

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]),
 torch.float32,
 2)

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(cudaResult.max())

# Find min
print(cudaResult.min())

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(cudaResult.argmax())

# Find arg min
print(cudaResult.argmin())


tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
# Create random tensor
# Remove single dimensions
# Print out tensors and their shapes

LAST_RANDOM_SEED = 7
torch.manual_seed(LAST_RANDOM_SEED)

tensor = torch.rand(1, 1, 1, 10)
tensorSqueezed = torch.squeeze(tensor)

tensor, tensor.shape, tensorSqueezed, tensorSqueezed.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))

In [ ]:
tensorNotSqueezed = tensorSqueezed.unsqueeze(dim=0)
tensorNotSqueezed, tensorNotSqueezed.shape

(tensor([[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
          0.8513]]),
 torch.Size([1, 10]))

In [ ]:
tensorNotNotSqueezed = tensorSqueezed.unsqueeze(dim=0)
for i in range(9):
  tensorNotNotSqueezed = tensorNotNotSqueezed.unsqueeze(dim=0)

tensorNotNotSqueezed, tensorNotNotSqueezed.shape

(tensor([[[[[[[[[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071,
                   0.6297, 0.3653, 0.8513]]]]]]]]]]]),
 torch.Size([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 10]))